dist: trusty

env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_TOKEN

language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install -g typescript
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run eslint-ci
  - npm run test

after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
